# Generated by Django 4.0.4 on 2022-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_fabrics_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrics',
            name='color',
            field=models.PositiveIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='fabric',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='partycode',
            field=models.CharField(max_length=10),
        ),
    ]
