# Generated by Django 4.0.4 on 2022-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_fabrics_color_alter_fabrics_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrics',
            name='maker',
            field=models.CharField(default='hg', max_length=15),
        ),
    ]
