# Generated by Django 4.0.3 on 2022-06-05 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_fabrics_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='maker',
            field=models.CharField(max_length=15),
        ),
    ]
