# Generated by Django 4.0.3 on 2022-06-24 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_fabrics_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrics',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabrics',
            name='cut_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 20, 17, 47, 456634)),
        ),
        migrations.AddField(
            model_name='fabrics',
            name='cutting',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='fabrics',
            name='gr_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabrics',
            name='hsb_clr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabrics',
            name='rec_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='color',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 20, 17, 47, 456634)),
        ),
    ]
