# Generated by Django 4.0.3 on 2022-06-28 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_fabrics_completed_fabrics_cut_time_fabrics_cutting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrics',
            name='item',
            field=models.CharField(default='layspant', max_length=20),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='cut_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 19, 53, 55, 996971)),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 19, 53, 55, 996971)),
        ),
    ]
