# Generated by Django 4.0.3 on 2022-06-28 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_fabrics_item_alter_fabrics_cut_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrics',
            name='cut_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 20, 12, 9, 303910)),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='item',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 20, 12, 9, 303910)),
        ),
    ]
