# Generated by Django 4.0.3 on 2022-06-28 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_fabrics_cut_time_alter_fabrics_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='cut_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 0, 25, 48, 81600)),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='cutting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 0, 25, 48, 81600)),
        ),
    ]
