# Generated by Django 4.0.3 on 2022-06-28 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_items_alter_fabrics_cut_time_alter_fabrics_cutting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrics',
            name='cut_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 0, 26, 32, 159395)),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 0, 26, 32, 159395)),
        ),
    ]
