# Generated by Django 4.0.3 on 2022-07-01 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_makers_alter_fabrics_cut_time_alter_fabrics_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrics',
            name='item',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 1, 30, 53, 151402)),
        ),
    ]
