# Generated by Django 4.0.3 on 2022-07-02 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_alter_fabrics_item_alter_fabrics_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 12, 28, 19, 483370)),
        ),
    ]
