# Generated by Django 4.0.3 on 2022-07-02 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_alter_fabrics_cut_time_alter_fabrics_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partycodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partycode', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 15, 6, 34, 951888)),
        ),
    ]
