# Generated by Django 4.0.3 on 2022-07-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_fabnames_partycodes_alter_fabrics_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='maker',
            field=models.ManyToManyField(to='stocks.makers'),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 17, 26, 8, 411776)),
        ),
    ]
