# Generated by Django 4.0.3 on 2022-07-04 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_items_maker_alter_fabrics_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrics',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 17, 28, 56, 774257)),
        ),
    ]
